language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test -- --coverage -u
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT