export const VALIDATE_SIGNUP = 'VALIDATE_SIGNUP';
export const FIND_USER = 'FIND_USER';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const LOGIN_USER = 'LOGIN_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
